name: Smart contracts

on:
  pull_request:
    branches:
      - "**"

defaults:
  run:
    working-directory: contracts/

jobs:
  test:
    name: âœ… Test
    runs-on: ubuntu-latest

    env:
      PRIVATE_KEY: "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
      POLYGON_ALCHEMY_KEY: "CLG_LCiDZkHaMGRaLQc_yhbhbSiv6NEL"
      ETH_ALCHEMY_KEY: "CLG_LCiDZkHaMGRaLQc_yhbhbSiv6NEL"
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ“¥ Download deps
        run: npm install

  gas_report:
    name: â›½ Gas Report

    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ“¥ Download deps
        run: npm install

      - name: Run Hardhat smart contract tests
        run: MINING=true REPORT_GAS=true npx hardhat test

  audit:
    name: ğŸ‘ï¸ Audit

    steps:
      - name: Install C4udit worker
        run: cd build && git clone https://github.com/byterocket/c4udit && cd c4udit && go build .

      - name: Run automated low-complexity C4udit worker
        run: cd build && ./c4udit/c4udit -s ../contracts/

  build:
    name: âš’ï¸ Build

    steps:
      - name: Save the build outputs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "fix: smart contract build"
