name: Smart contracts

on:
  pull_request:
    branches:
      - "**"

defaults:
  run:
    working-directory: contracts/

jobs:
  test:
    name: âœ… Test
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      POLYGON_ALCHEMY_KEY: ${{ secrets.POLYGON_ALCHEMY_KEY }}
      ETH_ALCHEMY_KEY: ${{ secrets.ETH_ALCHEMY_KEY }}
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ¢ Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: ğŸ“š List the state of node modules
        continue-on-error: true
        run: npm list

      - name: ğŸ“¥ Download deps
        run: npm install

      - name: ğŸ¤” Run smart contract tests
        run: MINING=true CI=true npx hardhat test

      - name: ğŸ—ï¸ Save build
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "fix: gas report"
  audit:
    name: ğŸ‘ï¸ Audit
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ“¥ Download deps
        run: cd build && git clone https://github.com/byterocket/c4udit && cd c4udit && go build .

      - name: ğŸ˜¡ Run contract auditor
        run: cd build && ./c4udit/c4udit -s ../contracts/

      - name: ğŸ—ï¸ Save build
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "fix: contract audit"
